"""Post model for generated and approved content."""

from __future__ import annotations

from datetime import datetime
from typing import Any
from uuid import UUID

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Index, Text, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PostgresUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.models.base import UUIDTimestampMixin


class Post(UUIDTimestampMixin, Base):
    """Content item generated by agents and managed until publication."""

    __tablename__ = "posts"
    __table_args__ = (
        CheckConstraint(
            "status IN ('rascunho', 'em_revisao', 'aprovado', 'agendado', 'publicado', 'rejeitado', 'arquivado')",
            name="ck_posts_status",
        ),
        CheckConstraint(
            "formato IN ('feed', 'story', 'reels', 'carrossel')",
            name="ck_posts_formato",
        ),
        Index("ix_posts_empresa_status", "empresa_id", "status"),
        Index("ix_posts_empresa_data_sugerida", "empresa_id", "data_publicacao_sugerida"),
        Index(
            "ix_posts_fluxo_pendente",
            "empresa_id",
            "data_publicacao_sugerida",
            postgresql_where=text("status IN ('rascunho', 'em_revisao', 'aprovado')"),
        ),
    )

    empresa_id: Mapped[UUID] = mapped_column(
        PostgresUUID(as_uuid=True),
        ForeignKey("empresas.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    calendario_editorial_id: Mapped[UUID | None] = mapped_column(
        PostgresUUID(as_uuid=True),
        ForeignKey("calendario_editorial.id", ondelete="SET NULL"),
        index=True,
    )
    servico_id: Mapped[UUID | None] = mapped_column(
        PostgresUUID(as_uuid=True),
        ForeignKey("servicos.id", ondelete="SET NULL"),
        index=True,
    )
    aprovado_por_usuario_id: Mapped[UUID | None] = mapped_column(
        PostgresUUID(as_uuid=True),
        ForeignKey("usuarios.id", ondelete="SET NULL"),
        index=True,
    )
    titulo: Mapped[str] = mapped_column(Text, nullable=False)
    formato: Mapped[str] = mapped_column(Text, default="feed", nullable=False)
    status: Mapped[str] = mapped_column(Text, default="rascunho", nullable=False)
    legenda: Mapped[str | None] = mapped_column(Text)
    cta: Mapped[str | None] = mapped_column(Text)
    hashtags: Mapped[list[str]] = mapped_column(JSONB, default=list, nullable=False)
    conteudo_estruturado: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        default=dict,
        nullable=False,
    )
    prompt_imagem: Mapped[str | None] = mapped_column(Text)
    data_publicacao_sugerida: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
    )
    aprovado_em: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    observacoes: Mapped[str | None] = mapped_column(Text)

    empresa: Mapped["Empresa"] = relationship(back_populates="posts")
    calendario_editorial: Mapped["CalendarioEditorial | None"] = relationship(
        back_populates="posts",
    )
    servico: Mapped["Servico | None"] = relationship(back_populates="posts")
    aprovado_por: Mapped["Usuario | None"] = relationship(
        back_populates="posts_aprovados",
        foreign_keys=[aprovado_por_usuario_id],
    )
    midias: Mapped[list["Midia"]] = relationship(
        back_populates="post",
        cascade="all, delete-orphan",
    )
    publicacoes: Mapped[list["Publicacao"]] = relationship(
        back_populates="post",
        cascade="all, delete-orphan",
    )
    prompts: Mapped[list["Prompt"]] = relationship(back_populates="post")

